/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-08 06:17:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import bbs.BbsDAO;
import bbs.Bbs;
import java.util.ArrayList;

public final class community_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("bbs.Bbs");
    _jspx_imports_classes.add("bbs.BbsDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>FriendsFit</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/slideStyle.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");

    String userID = null; // 로그인이 된 사람들은 로그인정보를 담을 수 있도록한다
    if (session.getAttribute("userID") != null){
        userID = (String)session.getAttribute("userID");
    }
    int pageNumber = 1; // 기본페이지 기본적으로 페이지 1부터 시작하므로
    if (request.getParameter("pageNumber") != null)
    {
        pageNumber = Integer.parseInt(request.getParameter("pageNumber"));
    }

      out.write("\n");
      out.write("	<div id=\"whole\">\n");
      out.write("        <div id=\"mainframe\">\n");
      out.write("            <div id=\"main-content\">\n");
      out.write("                <div id=\"header\">\n");
      out.write("                    <div class=\"top-header\">\n");
      out.write("                        <img src=\"img/FFlogo.png\" alt=\"friendsfit-logo\" style=\"cursor:pointer\" onclick=\"location.href='index.jsp'\">\n");
      out.write("                         <!-- <h1>Our fit</h1> -->\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"button-group\">\n");
      out.write("                        <form action=\"login.html\">\n");
      out.write("                            <button type=\"submit\" class=\"sign-in-button\" formaction=\"login.jsp\">\n");
      out.write("                                로그인\n");
      out.write("                                /\n");
      out.write("                                가입\n");
      out.write("                            </button>\n");
      out.write("                    </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <table class=\"table table-striped\" style=\"text-align:center; margin:auto; width:430px; min-height: 350px; border:1px solid #dddddd\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th style=\"background-color:#eeeeee; text-align:center;\">번호</th>\n");
      out.write("                        <th style=\"background-color:#eeeeee; text-align:center;\">제목</th>\n");
      out.write("                        <th style=\"background-color:#eeeeee; text-align:center;\">작성자</th>\n");
      out.write("                        <th style=\"background-color:#eeeeee; text-align:center;\">작성일</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                ");

                    BbsDAO bbsDAO = new BbsDAO();
                    ArrayList<Bbs> list = bbsDAO.getList(pageNumber);
                    for(int i = 0; i < list.size(); i++)
                    {
                
      out.write("\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>");
      out.print(list.get(i).getBbsID() );
      out.write("</td> <!-- 특수문자를 제대로 출력하기위해 & 악성스크립트를 방지하기위해 -->\n");
      out.write("                        <td><a href=\"communityView.jsp?bbsID=");
      out.print(list.get(i).getBbsID());
      out.write('"');
      out.write('>');
      out.print(list.get(i).getBbsTitle());
      out.write("</a></td>\n");
      out.write("                        <td>");
      out.print(list.get(i).getUserID() );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print(list.get(i).getBbsDate().substring(0,11) + list.get(i).getBbsDate().substring(11, 13) + "시" + list.get(i).getBbsDate().substring(14,16) + "분" );
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("            ");

                if(pageNumber != 1) {
            
      out.write("\n");
      out.write("                <a href=\"bbs.jsp?pageNumber=");
      out.print(pageNumber - 1 );
      out.write("\" class=\"btn btn-success btn-arrow-left\">이전</a>\n");
      out.write("            ");

                } if (bbsDAO.nextPage(pageNumber + 1)) {
            
      out.write("\n");
      out.write("                <a href=\"bbs.jsp?pageNumber=");
      out.print(pageNumber + 1 );
      out.write("\" class=\"btn btn-success btn-arrow-left\">다음</a>\n");
      out.write("            \n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("            <a href=\"communityWrite.jsp\" class=\"btn btn-primary pull-right\">글쓰기</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("                \n");
      out.write("                <div id=\"main\" style=\"background-color: white;\">\n");
      out.write("                \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div id=\"footer\">\n");
      out.write("                    <h1>FriendsFit</h1>\n");
      out.write("                    피트니스크루<br>\n");
      out.write("                    팀장 김대현: ysm691611@naver.com<br>\n");
      out.write("                    변지협 오주현 류혜림 염다영<br>\n");
      out.write("                    인공지능사관학교<br>\n");
      out.write("                    @all rights reserved+\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div id=\"main-navbar\" class=\"navbar\">\n");
      out.write("                <ul class=\"navbar-ul\">\n");
      out.write("                    <li class=\"navbar-li1 navbar-li\">\n");
      out.write("                    		<img src=\"img/nav_home.svg\" alt=\"home icon\" width=\"24\" height=\"24\" style=\"cursor:pointer\" onclick=\"location.href='index.jsp'\">\n");
      out.write("                    	<br>홈\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"navbar-li2 navbar-li\">                    	\n");
      out.write("                    		<img src=\"img/nav_map.svg\" alt=\"map icon\" width=\"24\" height=\"24\" style=\"cursor:pointer\" onclick=\"location.href='map.jsp'\">\n");
      out.write("                            <br>지도\n");
      out.write("                     </li>\n");
      out.write("                    <li class=\"navbar-li3 navbar-li\">\n");
      out.write("                    		<img src=\"img/nav_commu.svg\" alt=\"community icon\" width=\"24\" height=\"24\" style=\"cursor:pointer\" onclick=\"location.href='community.jsp'\">\n");
      out.write("                    		<br>커뮤니티\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"navbar-li4 navbar-li\">\n");
      out.write("	                    	<img src=\"img/nav_col.svg\" alt=\"column icon\" width=\"24\" height=\"24\" style=\"cursor:pointer\" onclick=\"location.href='column.jsp'\">\n");
      out.write("                    		<br>컬럼\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"navbar-li5 navbar-li\">\n");
      out.write("                    		<img src=\"img/nav_review.svg\" alt=\"review icon\" width=\"24\" height=\"24\" style=\"cursor:pointer\" onclick=\"location.href='review.jsp'\">\n");
      out.write("                        <br>ocr리뷰\n");
      out.write("                    </li>\n");
      out.write("				</ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
