/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-07 05:59:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"EUC-KR\">\n");
      out.write("<title>JoinPage</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/join.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- whole body -->\n");
      out.write("	\n");
      out.write("	<div id=\"whole\">\n");
      out.write("	   	 <div id=\"mainframe\">\n");
      out.write("	            <div id=\"main-content\">\n");
      out.write("	                <div id=\"header\">\n");
      out.write("	                    <div class=\"top-header\">\n");
      out.write("	                        <img src=\"img/FFlogo.png\" alt=\"friendsfit-logo\" style=\"cursor:pointer\" onclick=\"location.href='main.jsp'\">\n");
      out.write("	                    </div>\n");
      out.write("	                </div>\n");
      out.write("	                \n");
      out.write("	                <!-- join form -->\n");
      out.write("	                <div class=\"joinwrap\">\n");
      out.write("	                	<form id=\"joinForm\" name=\"joinForm\" action=\"\" method=\"post\" target=\"_self\" enctype=\"multipart/form-data\">\n");
      out.write("		                <div class=\"titleArea\">\n");
      out.write("	    					<h2>회원 가입</h2>\n");
      out.write("						</div>\n");
      out.write("						<hr class=\"line\">\n");
      out.write("						\n");
      out.write("						<!-- NOT NULL  -->\n");
      out.write("						\n");
      out.write("						<h3 class=\"basic\">기본정보</h3>\n");
      out.write("						<p class=\"required \">\n");
      out.write("							<img src=\"img/ico_required_red.jpg\" alt=\"필수\"> 필수입력사항\n");
      out.write("						</p>\n");
      out.write("						\n");
      out.write("						<div class=\"ec-base-table typeWrite\">\n");
      out.write("					        <table border=\"1\" summary=\"\">\n");
      out.write("								<caption>회원 기본정보</caption>\n");
      out.write("					        <colgroup>\n");
      out.write("								<col style=\"width:150px;\">\n");
      out.write("								<col style=\"width:auto;\">\n");
      out.write("							</colgroup>\n");
      out.write("							<tbody>\n");
      out.write("								<tr>\n");
      out.write("									<th scope=\"row\">\n");
      out.write("									아이디 \n");
      out.write("									<img src=\"img/ico_required_red.jpg\" alt=\"필수\">\n");
      out.write("									</th>\n");
      out.write("					                <td>\n");
      out.write("					                	<input id=\"member_id\" name=\"member_id\" fw-filter=\"isFill&amp;isFill&amp;isMin[4]&amp;isMax[16]&amp;isIdentity\" fw-label=\"아이디\" fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\" value=\"\" type=\"text\"> \n");
      out.write("					                	<span id=\"idMsg\"></span> \n");
      out.write("					                	(영문소문자/숫자, 4~16자)\n");
      out.write("					                </td>\n");
      out.write("					            </tr>\n");
      out.write("								<tr>\n");
      out.write("									<th scope=\"row\">\n");
      out.write("										비밀번호 \n");
      out.write("										<img src=\"img/ico_required_red.jpg\" alt=\"필수\">\n");
      out.write("									</th>\n");
      out.write("					                <td>\n");
      out.write("					                    <div class=\"eTooltip\">\n");
      out.write("					                        <input id=\"passwd\" name=\"passwd\" fw-filter=\"isFill&amp;isMin[4]&amp;isMax[16]\" fw-label=\"비밀번호\" fw-msg=\"\" autocomplete=\"off\" maxlength=\"16\" 0=\"disabled\" value=\"\" type=\"password\">                        \n");
      out.write("					                        <div class=\"ec-base-tooltip typeUpper\">\n");
      out.write("					                            <div class=\"content\">\n");
      out.write("					                                <strong class=\"txtWarn\">※ 비밀번호 입력 조건</strong>\n");
      out.write("					                                <ul class=\"ec-base-help typeDash gBlank10 txtWarn\">\n");
      out.write("					                					- 대소문자/숫자/특수문자 중 2가지 이상 조합, 10자~16자<br>\n");
      out.write("					                					- 입력 가능 특수문자 <br>\n");
      out.write("					                					&nbsp;&nbsp;&nbsp;  ~ ` ! @ # $ % ^ ( ) * _ - = { } [ ] | ; : &lt; &gt; , . ? /<br>\n");
      out.write("										                - 공백 입력 불가능 <br>\n");
      out.write("										                - 연속된 문자, 숫자 사용 불가능 <br>\n");
      out.write("										                - 동일한 문자, 숫자를 반복해서 사용 불가능 <br>\n");
      out.write("										                - 아이디 포함 불가능                                \n");
      out.write("										            </ul>\n");
      out.write("												</div>\n");
      out.write("					                            <a href=\"#none\" class=\"btnClose\" tabindex=\"-1\">\n");
      out.write("					                            	<img src=\"//img.echosting.cafe24.com/skin/base/common/btn_close_tip.gif\" alt=\"닫기\">\n");
      out.write("					                            </a>\n");
      out.write("					                            <span class=\"edge\"></span>\n");
      out.write("					                        </div>\n");
      out.write("					                    </div>\n");
      out.write("					                    (영문 대소문자/숫자/특수문자 중 2가지 이상 조합, 10자~16자)                \n");
      out.write("					                 </td>\n");
      out.write("					            </tr>\n");
      out.write("								<tr>\n");
      out.write("									<th scope=\"row\">\n");
      out.write("										비밀번호 확인 \n");
      out.write("										<img src=\"img/ico_required_red.jpg\" alt=\"필수\">\n");
      out.write("									</th>\n");
      out.write("					                <td>\n");
      out.write("					                	<input id=\"user_passwd_confirm\" name=\"user_passwd_confirm\" fw-filter=\"isFill&amp;isMatch[passwd]\" fw-label=\"비밀번호 확인\" fw-msg=\"비밀번호가 일치하지 않습니다.\" autocomplete=\"off\" maxlength=\"16\" 0=\"disabled\" value=\"\" type=\"password\"> \n");
      out.write("					                	<span id=\"pwConfirmMsg\"></span> \n");
      out.write("					                </td>\n");
      out.write("					            </tr>\n");
      out.write("								<tr>\n");
      out.write("									<th scope=\"row\" id=\"nameTitle\">\n");
      out.write("										이름 \n");
      out.write("										<img src=\"img/ico_required_red.jpg\" alt=\"필수\">\n");
      out.write("									</th>\n");
      out.write("					                <td>\n");
      out.write("					                	<input id=\"name_id\" name=\"name\" fw-filter=\"isFill&amp;isFill&amp;isMin[4]&amp;isMax[16]&amp;isIdentity\" fw-label=\"이름\" fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\" value=\"\" type=\"text\">\n");
      out.write("					                    <span id=\"nameContents\"></span>\n");
      out.write("					                </td>\n");
      out.write("					            </tr>\n");
      out.write("					\n");
      out.write("								<tr class=\"\">\n");
      out.write("									<th scope=\"row\">\n");
      out.write("									주소 \n");
      out.write("									<img src=\"img/ico_required_red.jpg\" alt=\"필수\">\n");
      out.write("									</th>\n");
      out.write("					                <td>\n");
      out.write("					                    <input id=\"postcode1\" name=\"postcode1\" fw-filter=\"isLengthRange[1][14]\" fw-label=\"우편번호1\" fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\" readonly=\"readonly\" maxlength=\"14\" value=\"\" type=\"text\">                    \n");
      out.write("					                    <a href=\"#none\" class=\"btnNormal\" onclick=\"\" id=\"postBtn\">우편번호\n");
      out.write("					                    </a>\n");
      out.write("					                    <br>\n");
      out.write("					                    <input id=\"addr1\" name=\"addr1\" fw-filter=\"\" fw-label=\"주소\" fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\" readonly=\"readonly\" value=\"\" type=\"text\"> \n");
      out.write("					                    기본주소\n");
      out.write("					                    <br>\n");
      out.write("					                    <input id=\"addr2\" name=\"addr2\" fw-filter=\"\" fw-label=\"주소\" fw-msg=\"\" class=\"inputTypeText\" placeholder=\"\" value=\"\" type=\"text\"> \n");
      out.write("					                    나머지주소 (선택입력가능)                \n");
      out.write("					                </td>\n");
      out.write("					            </tr>\n");
      out.write("					           </tbody>\n");
      out.write("					          </table>\n");
      out.write("					</div>\n");
      out.write("					<h3 class=\" \">추가정보</h3>\n");
      out.write("					<div class=\"ec-base-table typeWrite \">\n");
      out.write("						<table border=\"1\" summary>\n");
      out.write("							<caption>회원 추가정보</caption>\n");
      out.write("							<colgroup>\n");
      out.write("								<col style=\"width:150px;\">\n");
      out.write("								<col style=\"width:auto;\">\n");
      out.write("							</colgroup>\n");
      out.write("							<tbody>\n");
      out.write("								<tr class=\"\">\n");
      out.write("									<th scope=\"row\">\n");
      out.write("										나이\n");
      out.write("									</th>\n");
      out.write("									<td>\n");
      out.write("									<input id=\"age\" name=\"age\" fw-filter=\"\" fw-label=\"나이\" fw-msg=\"\" class=\"inputTypeNum\" placeholder=\"\" maxlength=\"4\" value=\"\" type=\"number\">\n");
      out.write("										세\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr class=\"\">\n");
      out.write("									<th scope=\"row\">\n");
      out.write("										연락처\n");
      out.write("									</th>\n");
      out.write("									<td>\n");
      out.write("										<select id=\"mobile1\" name=\"mobile[]\" fw-filter=\"isNumber\" fw-label=\"휴대전화\" fw-alone=\"N\" fw-msg=\"\">\n");
      out.write("											<option value=\"010\">010</option>\n");
      out.write("											<option value=\"011\">011</option>\n");
      out.write("											<option value=\"016\">016</option>\n");
      out.write("											<option value=\"017\">017</option>\n");
      out.write("											<option value=\"018\">018</option>\n");
      out.write("											<option value=\"019\">019</option>\n");
      out.write("											<option value=\"02\">02</option>\n");
      out.write("											<option value=\"031\">031</option>\n");
      out.write("											<option value=\"032\">032</option>\n");
      out.write("											<option value=\"033\">033</option>\n");
      out.write("											<option value=\"041\">041</option>\n");
      out.write("											<option value=\"042\">042</option>\n");
      out.write("											<option value=\"043\">043</option>\n");
      out.write("											<option value=\"044\">044</option>\n");
      out.write("											<option value=\"051\">051</option>\n");
      out.write("											<option value=\"052\">052</option>\n");
      out.write("											<option value=\"053\">053</option>\n");
      out.write("											<option value=\"054\">054</option>\n");
      out.write("											<option value=\"055\">055</option>\n");
      out.write("											<option value=\"061\">061</option>\n");
      out.write("											<option value=\"062\">062</option>\n");
      out.write("											<option value=\"063\">063</option>\n");
      out.write("											<option value=\"064\">064</option>\n");
      out.write("											<option value=\"0502\">0502</option>\n");
      out.write("											<option value=\"0503\">0503</option>\n");
      out.write("											<option value=\"0504\">0504</option>\n");
      out.write("											<option value=\"0505\">0505</option>\n");
      out.write("											<option value=\"0506\">0506</option>\n");
      out.write("											<option value=\"0507\">0507</option>\n");
      out.write("											<option value=\"0508\">0508</option>\n");
      out.write("											<option value=\"070\">070</option>\n");
      out.write("										</select>\n");
      out.write("											-\n");
      out.write("											<input id=\"mobile2\" name=\"mobile[]\" maxlength=\"4\" fw-filter=\"isNumber\" fw-label=\"휴대전화\" fw-alone=\"N\" fw-msg=\"\" value=\"\" type=\"text\">\n");
      out.write("											-\n");
      out.write("											<input id=\"mobile3\" name=\"mobile[]\" maxlength=\"4\" fw-filter=\"isNumber\" fw-label=\"휴대전화\" fw-alone=\"N\" fw-msg=\"\" value=\"\" type=\"text\">\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr class=\"\">\n");
      out.write("									<th scope=\"row\">\n");
      out.write("										운동경력\n");
      out.write("									</th>\n");
      out.write("									<td>\n");
      out.write("										<select id=\"career\" name=\"career\" fw-filter fw-label=\"운동경력\" fw-msg>\n");
      out.write("											<option value selected=\"selected\">선택</option>\n");
      out.write("											<option value=\"career_01\">입문</option>\n");
      out.write("											<option value=\"career_02\">초급</option>\n");
      out.write("											<option value=\"career_03\">중급</option>\n");
      out.write("											<option value=\"career_04\">고급</option>\n");
      out.write("											<option value=\"career_05\">전문가</option>\n");
      out.write("										</select>\n");
      out.write("									</td>\n");
      out.write("								</tr>\n");
      out.write("							</tbody>\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<div class=\"ec-base-button\">\n");
      out.write("        				<a href=\"#none\" class=\"btnSubmitFix sizeM\" onclick=\"memberJoinAction()\">회원가입</a>\n");
      out.write("    				</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("		</div>\n");
      out.write("	</div>	               \n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
