/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-08-07 01:35:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.reviewComment_memberDTO;
import java.util.ArrayList;
import com.model.reviewSelectDTO;
import com.model.dbDAO;

public final class reviewSee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.model.dbDAO");
    _jspx_imports_classes.add("com.model.reviewSelectDTO");
    _jspx_imports_classes.add("com.model.reviewComment_memberDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>FriendsFit</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/slideStyle.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div id=\"whole\">\n");
      out.write("		<div id=\"mainframe\">\n");
      out.write("			<div id=\"main-content\">\n");
      out.write("				<div id=\"header\">\n");
      out.write("					<div class=\"top-header\">\n");
      out.write("						<img src=\"img/FFlogo.png\" alt=\"friendsfit-logo\"\n");
      out.write("							style=\"cursor: pointer\" onclick=\"location.href='index.jsp'\">\n");
      out.write("						<!-- <h1>Our fit</h1> -->\n");
      out.write("					</div>\n");
      out.write("					<div class=\"button-group\">\n");
      out.write("						<form action=\"login.html\">\n");
      out.write("							<button type=\"submit\" class=\"sign-in-button\"\n");
      out.write("								formaction=\"login.jsp\">로그인 / 가입</button>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div id=\"main\" style=\"background-color: white;\">\n");
      out.write("\n");
      out.write("					<div class=\"reviewWrite\">\n");
      out.write("						<a href=\"reviewWrite.jsp\">리뷰쓰기</a>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"reviewcontainer\">\n");
      out.write("\n");
      out.write("\n");
      out.write("				");

				request.setCharacterEncoding("UTF-8");
				response.setCharacterEncoding("UTF-8");
					  String reviewNum = request.getParameter("reviewNum");
					  int intReviewNum = Integer.parseInt(reviewNum);
					  System.out.println(reviewNum);
					  System.out.println(intReviewNum);
					  
					  
					  dbDAO dbdao = new dbDAO();
					  reviewSelectDTO review = dbdao.getReview(intReviewNum);
					  request.setAttribute("review", review);
				
      out.write("\n");
      out.write("\n");
      out.write("						<div class=\"community-list-item\">\n");
      out.write("							<div class=\"CommunityListItem__StyledListItemContent\">\n");
      out.write("								<div class=\"CommunityListItem__bill\">영수증후기</div>\n");
      out.write("								<div class=\"CommunityListItem__id\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("								<div class=\"CommunityListItem__point\">(포인트)</div>\n");
      out.write("								<div class=\"CommunityListItem__registerDate\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.registerDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("								<div class=\"CommunityListItem__content\"></div>\n");
      out.write("							</div>\n");
      out.write("							<section class=\"CommunityListItem__StyledCommunityActionBar\">\n");
      out.write("								<button class=\"like-button\">\n");
      out.write("									<img src=\"img/like-icon.svg\">\n");
      out.write("									<div>좋아요</div>\n");
      out.write("									<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewLike}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("								</button>\n");
      out.write("								<button class=\"like-button\">\n");
      out.write("									<img src=\"img/comment-icon.svg\">\n");
      out.write("									<div>댓글</div>\n");
      out.write("									<div>(댓글수)</div>\n");
      out.write("								</button>\n");
      out.write("								<button class=\"like-button\">\n");
      out.write("									<img src=\"img/views-icon.svg\">\n");
      out.write("									<div>조회수</div>\n");
      out.write("									<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewViews}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("								</button>\n");
      out.write("							</section>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<!-- 리뷰쓰기 -->\n");
      out.write("					<form action=\"reviewCommentAction\" method=\"post\">\n");
      out.write("						");
      out.print( reviewNum );
      out.write("\n");
      out.write("						<div class=\"review-comment-textarea\">\n");
      out.write("							<input name=\"rNum\" value=\"");
      out.print( reviewNum );
      out.write("\" style=\"display: none;\">\n");
      out.write("							<textarea name=\"reviewComment\" maxlength=\"440\"\n");
      out.write("								data-testid=\"comment-textarea\" placeholder=\"댓글을 입력해주세요.\"\n");
      out.write("								class=\"CommunityDetailTemplate__StyledCommentTextarea-sc-alice7-27\"\n");
      out.write("								style=\"height: 24px !important;\"></textarea>\n");
      out.write("							<div\n");
      out.write("								class=\"CommunityDetailTemplate__StyledTextareaButtonsArea-sc-alice7-28 ljKWyy\">\n");
      out.write("								<button type=\"reset\"\n");
      out.write("									class=\"CommunityDetailTemplate__StyledCommentActionButton-sc-alice7-29 eLDXiU\">취소</button>\n");
      out.write("								<button type=\"submit\"\n");
      out.write("									class=\"CommunityDetailTemplate__StyledCommentActionButton-sc-alice7-29 jvbKoX\">등록</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("					<!-- 리뷰 보기 -->\n");
      out.write("					");
 ArrayList<reviewComment_memberDTO> rcmdto = dbdao.getReviewComment(intReviewNum);
						for(int i=0; i<rcmdto.size(); i++) { 
      out.write("\n");
      out.write("					\n");
      out.write("					<div class=\"review-wrapper\">\n");
      out.write("						<div class=\"comment-list-item\">\n");
      out.write("							<div class=\"comment-list-item-content\">\n");
      out.write("								<div class=\"comment-user-profile\">\n");
      out.write("									<div class=\"comment-user\"></div>\n");
      out.write("									<div class=\"user-tag\">");
      out.print( rcmdto.get(i).getId() );
      out.write("</div>\n");
      out.write("									<div class=\"create-time-wrapper\"> ");
      out.print( rcmdto.get(i).getPoint() );
      out.write("</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"comment-contents\"> ");
      out.print( rcmdto.get(i).getContent() );
      out.write(" </div>\n");
      out.write("								<div class=\"comment-action-area\">\n");
      out.write("									<div class=\"community-detail\">\n");
      out.write("										<button class=\"comment-like-button\">\n");
      out.write("											<img data-testid=\"thumbs-up-off-icon\"\n");
      out.write("												src=\"/imag/black-thumb-up-icon.svg\"\n");
      out.write("												alt=\"thumb up off icon\">\n");
      out.write("											<div> ");
      out.print( rcmdto.get(i).getRegisterDate() );
      out.write(" </div>\n");
      out.write("										</button>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					");
 } 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div id=\"footer\">\n");
      out.write("					<h1>FriendsFit</h1>\n");
      out.write("					피트니스크루<br> 팀장 김대현: ysm691611@naver.com<br> 변지협 오주현 류혜림\n");
      out.write("					염다영<br> 인공지능사관학교<br> @all rights reserved+\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div id=\"main-navbar\" class=\"navbar\">\n");
      out.write("				<ul class=\"navbar-ul\">\n");
      out.write("					<li class=\"navbar-li1 navbar-li\"><img src=\"img/nav_home.svg\"\n");
      out.write("						alt=\"home icon\" width=\"24\" height=\"24\" style=\"cursor: pointer\"\n");
      out.write("						onclick=\"location.href='index.jsp'\"> <br>홈</li>\n");
      out.write("					<li class=\"navbar-li2 navbar-li\"><img src=\"img/nav_map.svg\"\n");
      out.write("						alt=\"map icon\" width=\"24\" height=\"24\" style=\"cursor: pointer\"\n");
      out.write("						onclick=\"location.href='map.jsp'\"> <br>지도</li>\n");
      out.write("					<li class=\"navbar-li3 navbar-li\"><img src=\"img/nav_commu.svg\"\n");
      out.write("						alt=\"community icon\" width=\"24\" height=\"24\"\n");
      out.write("						style=\"cursor: pointer\" onclick=\"location.href='community.jsp'\">\n");
      out.write("						<br>커뮤니티</li>\n");
      out.write("					<li class=\"navbar-li4 navbar-li\"><img src=\"img/nav_col.svg\"\n");
      out.write("						alt=\"column icon\" width=\"24\" height=\"24\" style=\"cursor: pointer\"\n");
      out.write("						onclick=\"location.href='column.jsp'\"> <br>컬럼</li>\n");
      out.write("					<li class=\"navbar-li5 navbar-li\"><img src=\"img/nav_review.svg\"\n");
      out.write("						alt=\"review icon\" width=\"24\" height=\"24\" style=\"cursor: pointer\"\n");
      out.write("						onclick=\"location.href='review.jsp'\"> <br>ocr리뷰</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
